### ISSUE TITLE
Support for Starsiege

### ISSUE THREAD

**Issue by EsjayDev** [sonicsnes/node-gamedig#100]
Starsiege is part of the Earthsiege series, not the Tribes:Starsiege game. It would be highly appreciated.

**Comment by sonicsnes** [comment]
Hi, aside from the wikipedia page, I can't even find many details about Starsiege. Is there a server up somewhere? Perhaps a single server? I'm not sure if we'll have much luck finding the query protocol, but perhaps just by chance we already have it implemented for another game.

**Comment by sonicsnes** [comment]
Found some super old query code on google from 2004, as well as some live servers on master1.starsiege.io:29000 (which seems to use the same master protocol as tribes 1).

Support added in gamedig 2.0.2.
