### ISSUE TITLE
Special character in ip address

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#101]
Hi ! I have this ip address : minecraft.néolithic.fr

```
		Gamedig.query({
			type: 'minecraftping',
			host: 'minecraft.néolithic.fr',
			port: 27230,
			port_query: 27230
		},
```

And i get this console error:

`Error: getaddrinfo ENOTFOUND minecraft.n�olithic.fr
`
How to make gamedig accept special characters ?

Thank you in advance

**Comment by Genteure** [comment]
You can use [punycode.js](https://github.com/bestiejs/punycode.js/) or any other punycode library to convert domain name before passing it to gamedig.

**Comment by sonicsnes** [comment]
Yep! Genteure is right on.

Special characters in hostnames is typically something that's accepted by your browser, but isn't actually the final hostname being used for the request.

If it's convenient, I guess we could build punycode support into gamedig, but it does seem to be a bit outside the scope. Do libraries like `request` accept punycode-encoded hosts?

**Comment by sonicsnes** [comment]
`request` works with punycode out of the box, and it turns out we already had a transitive dependency on punycode anyways, so I went ahead and baked support into Gamedig 2.0.6.
