### ISSUE TITLE
Interested in getting Vice City Multiplayer working

### ISSUE THREAD

**Issue by bbashy** [sonicsnes/node-gamedig#106]
I see a vcmp in the [reference folder](https://github.com/sonicsnes/node-gamedig/blob/master/reference/vcmp/lgsl.txt) but not too keen on doing it myself.

Looking to host servers for this game so if someone would like to run through this and help get it working with me, that would be great.

I think everything is there but I've got this http://wiki.vc-mp.org/wiki/Query_Mechanism

**Comment by sonicsnes** [comment]
Added in 2.0.9
