### ISSUE TITLE
Natural Selection 2 wont respond

### ISSUE THREAD

**Issue by Azperin** [sonicsnes/node-gamedig#109]
Tried to get information about ns2 server (82.199.102.133:27015), but get nothing, always says "Server is offline" 

What i did:
1. type: 'ns2', host: '82.199.102.133', with default games.txt
2. type: 'ns2', host: '82.199.102.133:27015', with default games.txt
3. type: 'ns2', host: '82.199.102.133', with port=27015 in games.txt

help please

**Comment by sonicsnes** [comment]
Please feel free to re-open if this is still an issue 😄
