### ISSUE TITLE
TCP Watchdog Timeout for some minecraft servers

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#112]
Hi ! For a long time I get the "TCP Watchdog Timeout" error for the following minecraft servers (all these servers work with port 25565):

pvp.bloodsymphony.com
play.skyfight.fr
mc.topcraft.fr

I tested locally on my computer and it works but not on my web servers. Do you have an idea ?

Query work perfectly on this minecraft servers (on local and on my web servers):

play.warzaria.net
Suncraft.minesr.com
PLAY.MCROYAL.FR

Can be a firewall block ? Which port should I open ?

Thank you in advance
David

**Comment by sonicsnes** [comment]
Hmm, that is a strange one. If it works locally, it certainly does sound like a firewall problem.

Minecraft just makes a simple tcp connection to the game port (25565) -- it's much more simple than other games that require udp packets or separate ports. It may be worth asking your hosting provider why you are unable to make outgoing tcp connections to port 25565.

**Comment by Murgator** [comment]
What is even stranger is that the query works perfectly with these minecraft servers:

play.warzaria.net
Suncraft.minesr.com
PLAY.MCROYAL.FR

However, they use the same port (25565), so logically, this is not a firewall problem ....

I'm lost

**Comment by Murgator** [comment]
Hi sonicsnes ! I solved the problem, these Minecraft servers are french and they block all connections from other countries. 

My local computer is in France and my web server is in germany ... ^^

Thanks for your response !

**Comment by sonicsnes** [comment]
Interesting, I would not have expected that! Thanks for reporting back 😃
