### ISSUE TITLE
Query fails when using a TCP protocol on Node 8

### ISSUE THREAD

**Issue by ZxFrankxZ** [sonicsnes/node-gamedig#113]
/rbd/pnpm-volume/eacb65dd-3829-45ed-9ea1-77e67484c4a4/node_modules/.registry.npmjs.org/gamedig/2.0.13/node_modules/gamedig/protocols/core.js:253

                        socket.off('data', onData);
                               ^
    TypeError: socket.off is not a function
    at Socket.onData (/rbd/pnpm-volume/eacb65dd-3829-45ed-9ea1-77e67484c4a4/node_modules/.registry.npmjs.org/gamedig/2.0.13/node_modules/gamedig/protocols/core.js:253:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

**Comment by ZxFrankxZ** [comment]
https://gyazo.com/175c8798f25bdbb6ca9acd96872b8192
https://gyazo.com/e5ea55c684cb7daaa114214ca84e6543

**Comment by sonicsnes** [comment]
Thanks for the report. Seems that Socket.off was added in node 10 (making
our requirement on node 8 incorrect). This was not on purpose, we should be
using Socket.removeListener instead. I will publish a patch tonight.

**Comment by ZxFrankxZ** [comment]
but it throw this error after the 2.0.0 version

**Comment by sonicsnes** [comment]
Correct. This code was added in gamedig 2.0.0, but the Socket.off API was
not added until nodejs 10. Since we advertise that gamedig works with
nodejs 8, we'll need to replace all calls to Socket.off with
Socket.removeListener.

**Comment by ZxFrankxZ** [comment]
Okey, and 1 question. Why i cant see the players? 
      players: [ {}, {}, {}, {}, {}, {} ],

**Comment by sonicsnes** [comment]
This is answered in the readme. Some protocols do not return player names
at all, so all you can tell is the number online (with players.length).
There is nothing we can do about this.

**Comment by sonicsnes** [comment]
This is fixed in gamedig 2.0.14.
