### ISSUE TITLE
JavaScript heap out of memory (minecraft.js)

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#114]
Hi ! I have a strange error when I ask this server with minecraftping: Freebuild.mine.bz:25565

![error minecraft server bug](https://user-images.githubusercontent.com/38978895/53293675-79f3df80-37d8-11e9-98e7-8f12812b3d34.png)

The problem is that this server crashes my script ...

Is there a solution to prevent this crash ?

This problem occur in local and on my web server...

I use gamedig to query thousands of different game servers and I have never had this problem before, only with this Minecraft server.

Thank you in advance.
David

**Comment by Genteure** [comment]
I cannot reproduce this problem on my computer.

```text
Windows 10 1809
gamedig@2.0.14

> node -v
v10.13.0
> npm -v
6.8.0

> gamedig --type minecraft --host freebuild.mine.bz --port 25565 --pretty
{
  "name": "",
  "map": "",
  "password": false,
  "raw": {
    "description": {
      "text": "Freebuild"
    },
    "players": {
      "max": 1000000000,
      "online": 423685411,
      "sample": [
        {
          "id": "cc8ba061-e894-472b-bbc0-20945286ec3b",
          "name": "§8§O|Mortal|§fBauerPower06§r"
        },
        {
          "id": "9e2fe3aa-c341-470e-aaf1-6d44e369cf98",
          "name": "§6|Royal|§f Zombie_Assassin5§6|$$$|§r"
        },
        {
          "id": "302297a0-2e3f-4f03-bd94-18009a6dfc12",
          "name": "§9|Prophet|§f shaggyolsen§6|§4LavaKing§6|§r"
        },
        {
          "id": "6f1a4e8d-84eb-4fd1-bb5e-726001b6925d",
          "name": "§8§O|Mortal|§fIbbycoolkid§r"
        },
        {
          "id": "18ea979c-9e76-4e19-a5cb-a1ebdb945bca",
          "name": "§l§7§kOU§b§nSiddiet§l§7§kOU§r"
        }
      ]
    },
    "version": {
      "name": "Spigot 1.13.2",
      "protocol": 404
    },
    "rcvNumPlayers": 423685411
  },
  "maxplayers": 1000000000,
  "players": [],
  "bots": [],
  "connect": "freebuild.mine.bz:25565",
  "ping": 210
}
```

**Comment by Genteure** [comment]
Are you using a version of gamedig below 2.0.12?
This server is returning `423685411` as online player number, that would cause gamedig to create a array with `543685411` element before 2.0.12.
see https://github.com/sonicsnes/node-gamedig/commit/2ffeda6098c19af66bedaa47a9de4eec64481b54

**Comment by sonicsnes** [comment]
@Genteure is exactly correct. Versions before 2.0.12 would attempt to allocate 423 million player objects, because the server is lying about how many players are online. After 2.0.12, these servers will simply get an empty player array.
