### ISSUE TITLE
2.0.0 port_query issue

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#115]
Hi, since I updated Gamedig, the port_query argument no longer exists. It works with most servers....

But I have a problem with some servers, for example on these two ARK:SE servers:

```
54.39.28.45:7780 (port_query: 27020)
147.135.30.49:5761 (port_query: 57561)
```

I get the following error:
![7a4fd34aade1a7d4457166e0297a822a](https://user-images.githubusercontent.com/38978895/53564329-e2cfb480-3b56-11e9-81b2-3a4c6816c10b.png)

I tested the commands below and I still get this error. Yet these servers are online if I use the old version of gamedig (specifying port AND port_query):

```
type: "arkse", host: "54.39.28.45", port: "7780", socketTimeout: 5000
type: "arkse", host: "54.39.28.45", port: "27020", socketTimeout: 5000

type: "arkse", host: "147.135.30.49", port: "5761", socketTimeout: 5000
type: "arkse", host: "147.135.30.49", port: "57561", socketTimeout: 5000
```

Thank you in advance for your response.

David

**Comment by bbashy** [comment]
I can't get any combination working for those servers. I'm using `gamedig@2.0.12` and `gamedig@1.0.46`.

Can you give me the command you got working on v1?

**Comment by sonicsnes** [comment]
I can't seem to get these to respond properly, even with v1. The first server times out immediately, while the second one doesn't seem to accept the challenge key that it provides.

**Comment by Murgator** [comment]
after a new test I finally get the same result as you. It's strange but I think we can close sorry and thank you for your help.
