### ISSUE TITLE
TCP Closed minecraft server

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#120]
Hi there ! I have a new issue with this Minecraft server: play.revene.net:25565

![error](https://user-images.githubusercontent.com/38978895/54922264-0e507f80-4f08-11e9-9ac0-3c6436e4bd93.png)

Same problem with minecraftpe protocol.

The server is currently online.

Thank you for your help.

**Comment by sonicsnes** [comment]
Do you have query_enabled and query_port set in your bungeecord config.yml? These settings should work with gamedig's minecraftbe protocol (you can't use the standard minecraft protocol with bungeecord, as it will respond with incorrect filler info).

**Comment by sonicsnes** [comment]
Please re-open if you are still encountering this issue 😄
