### ISSUE TITLE
Can't connect to CSGO/CSS server.

### ISSUE THREAD

**Issue by hcjordao** [sonicsnes/node-gamedig#122]
`
Gamedig.query({
            name: 'csgo',
            host: '172.107.208.2',
            port: 20100,
            debug: true
        }).then((state) => {
            console.log(state);
        }).catch((error) => {
            console.log(error.stack);
        });
`
Keep getting error: 
Error: No game specified.

**Comment by sonicsnes** [comment]
The key for game type is `type`, not `name`.
