### ISSUE TITLE
Error: UNKNOWN: unknown error, open '\\..\games.txt\'

### ISSUE THREAD

**Issue by Evald24** [sonicsnes/node-gamedig#123]
Error: UNKNOWN: unknown error, open '\\..\games.txt\'
version: gamedig@2.0.14
nodejs: v10.
OS: Windows 10.15.3
Webpack config
```
{
  test: /node_modules[\/\\](iconv-lite)[\/\\].+/,
  resolve: {
    aliasFields: [ 'main' ]
  }
}
```

**Comment by sonicsnes** [comment]
Gamedig is not usable in webpack / frontend applications. It's intended to be used only in a nodejs backend. Browsers cannot support sending the required udp packets for most query protocols.
