### ISSUE TITLE
Error:  Cannot find module 'dns'

### ISSUE THREAD

**Issue by BlacKlyExactly** [sonicsnes/node-gamedig#124]
![image](https://user-images.githubusercontent.com/44273038/57161473-fc59da80-6deb-11e9-8cd6-bfd3a8431024.png)

**Comment by sonicsnes** [comment]
Gamedig is not usable in webpack / frontend applications. It's intended to be used only in a nodejs backend. Browsers cannot support sending the required udp packets for most query protocols.
