### ISSUE TITLE
Cannot get infromation of Minecraft server on same host

### ISSUE THREAD

**Issue by WakanaYuki** [sonicsnes/node-gamedig#126]
When I try to get the information of my locally running minecraft server on my linux vps, I get an error (doesn't matter if link URL or localhost). But if I try to remotely get the minecraft server information (with my Windows VPS) it works like a charm.
And yes, I use the standard port (but have another running on a custom one, I can't get information of either of those when running the programm on the same server).

**Comment by sonicsnes** [comment]
Not sure how to reproduce this without more information. Please re-open if this is still an issue.
