### ISSUE TITLE
Memory useage, with starmade.js

### ISSUE THREAD

**Issue by Starystars67** [sonicsnes/node-gamedig#129]
![image](https://user-images.githubusercontent.com/15389482/59346921-4d25f280-8d0b-11e9-8f9a-eeab1c397330.png)

Hello, i came to my program today to find that this had happened. As you can see it is something to do with the starmade.js file and relates to garbage collection. Not sure how else to help but i figured it was worth reporting.

**Comment by sonicsnes** [comment]
Just to double-check, are you on the latest version of gamedig (2.0.14)? Previously, this could occur if the server reported a ton of players (either due to a bug, or if the server has been modded to fib about it), as gamedig would attempt to create a separate object for each one.

**Comment by Starystars67** [comment]
Huh interesting, i only installed the package 2 days ago but it seems to have installed version 1.0.49. I will update to that version and update.
