### ISSUE TITLE
DNS lookup return undefined and IP not found

### ISSUE THREAD

**Issue by neilzar** [sonicsnes/node-gamedig#135]
I have been experiencing some issues using gamedig. Everything worked fine when testing on my Windows 10 PC, but once I ran it on our CentOS 7 cloud server it started causing issues.

First of all, I have the following try, catch that performs a gamedig query to our Arma 3 servers.
```
try {
        var state = await gamedig.query({
            type: 'arma3',
            host: server.ip,
            port: server.port,
            debug: true
        });
        // handle state
    } catch (e) {
        // handle error
    }
```
server.ip and server.port are defined in a .json file because I am running this for 5 servers. The issue arises when I use a DNS address rather than a regular IP.

When using either arma1.fkservers.eu or arma2.fkservers.eu, it returns the following debug:
```
1|ARABot   | Q#0 DNS Lookup: arma1.fkservers.eu
1|ARABot   | Q#0 Standard Resolve: arma1.fkservers.eu
1|ARABot   | Q#0 Found address: undefined
1|ARABot   | Q#0 Requesting info ...
1|ARABot   | Q#0 undefined:2303 UDP-->
```
Obviously, that isn't what is supposed to happen and it only happens when I run it using PM2 on CentOS. On Windows, I had zero issues with this, and even when using the command line on CentOS it works without issues. It is just when I run the JS script with PM2. I used the following in the command line: `node node_modules/gamedig/bin/gamedig.js --type arma3 arma2.fkservers.eu`

The fun doesn't stop there though. arma1 works fine when I replace it with the normal IP, but arma2 also won't work if I use the normal IP, it returns the following error.
```
1|ARABot  | UDP ERROR: Error: getaddrinfo ENOTFOUND 95.216.77.99
1|ARABot  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
1|ARABot  | Q#59 UDP timeout detected
```
Again, this is not an issue in the command line or on Windows.

We performed a packet trace at first, and they showed no packets going out to those addresses; not a big surprise if it can't find the IP.

**Comment by sonicsnes** [comment]
That is... very strange. Almost looks like some sort of dns issue on the server? I have no idea why node would even be calling getaddrinfo if the packet was being sent to an IP rather than an address. Are you able to ping `arma2.fkservers.eu` from the server?

**Comment by neilzar** [comment]
Yes, I was able to successfully ping that server and also get the information of that server through the command line. It is only when running the script using pm2 that it fails.

**Comment by sonicsnes** [comment]
Is it possible you are running pm2 with container integration? If gamedig is being run from within a container, perhaps it has some differences in its networking config?

**Comment by neilzar** [comment]
I don't believe we do. Unless that is set up by default. I'll try to check if there is some networking config discrepancy.

**Comment by neilzar** [comment]
I just did a quick debug, ran the following dns lookup in the program for debug: 
```
dns.lookup('arma2.fkservers.eu', (error, address, family) => { console.log(`error: ${error}; address: ${address}; family ${family}`); });
```
and it returned `error: null; address: 95.216.77.99; family 4`, which seems correct to me. So I don't know why it then can't resolve when querying gamedig. `dns.resolve()` also gives the correct IP. For both arm2 and arma1

**Comment by neilzar** [comment]
Just for the sake of having the complete debug when using the ipv4 address for arma2.fkservers.eu:
```
1|ARABot  | Q#23 Query is running with options: { socketTimeout: 2000,
1|ARABot  |   attemptTimeout: 10000,
1|ARABot  |   maxAttempts: 1,
1|ARABot  |   port: 2302,
1|ARABot  |   protocol: 'valve',
1|ARABot  |   type: 'arma3',
1|ARABot  |   host: '95.216.77.99',
1|ARABot  |   debug: true }
1|ARABot  | Q#23 DNS Lookup: 95.216.77.99
1|ARABot  | Q#23 Raw IP Address: 95.216.77.99
1|ARABot  | Q#23 Requesting info ...
1|ARABot  | Q#23 95.216.77.99:2302 UDP-->
1|ARABot  | Q#23 Buffer length: 25 bytes
1|ARABot  | ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
1|ARABot  |             T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
1|ARABot  | 65 72 79 00
1|ARABot  | e  r  y
1|ARABot  | UDP ERROR: Error: getaddrinfo ENOTFOUND 95.216.77.99
1|ARABot  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
1|ARABot  | Q#23 UDP timeout detected
1|ARABot  | Q#23 Query failed with error Error: UDP - Timed out after 2000ms
1|ARABot  |     at Timeout.setTimeout (/home/botuser/discord-ara-bot/node_modules/gamedig/lib/Promises.js:7:25)
1|ARABot  |     at ontimeout (timers.js:436:11)
1|ARABot  |     at tryOnTimeout (timers.js:300:5)
1|ARABot  |     at listOnTimeout (timers.js:263:5)
1|ARABot  |     at Timer.processTimers (timers.js:223:10)
```

**Comment by neilzar** [comment]
I didn't find any issues with the network config, and we are not running it with container integration. And as I said two comments above I can still use `dns.lookup()` when called from the program ran with pm2. Also didn't find out anything new in the mean time.

**Comment by sonicsnes** [comment]
Gamedig makes the connection in two steps. First, it resolves the dns entry (which sounds like it's working properly), then it attempts to send a UDP packet to that resolved IP. For some reason, it sounds like your instance is attempting to lookup the ip address using the dns resolver during the process of sending the UDP packet -- and fails.

I'm still not certain why node would be doing a dns resolution at all, since it's being instructed to send the packet to a raw IP which obviously doesn't need resolved.

**Comment by sonicsnes** [comment]
Perhaps your server has some sort of strange ipv6 setup? I'm mostly just grasping at straws, but I'm not sure why else it would try doing a dns resolution of an ipv4 address. Although, you say that pinging the address works, so that's probably not it.

**Comment by sonicsnes** [comment]
Which version of node are you using?

**Comment by sonicsnes** [comment]
Poking through the nodejs core, GetAddrInfoReqWrap.onlookup should absolutely not be getting called at all if the parameter is a valid IP address. The dns lookup function is [bypassed entirely](https://github.com/nodejs/node/blob/df936c592596855ec9ad1141692faf0dc74f46f3/lib/dns.js#L128) if the input matches the IP pattern, so that leaves me with only two guesses.

1. Is there an invisible character hiding in the IP address? Is that domain in your /etc/hosts file? Perhaps it has some hidden character in it?
2. Is your node.js out of date? Perhaps this is related to some issue in an older version?

**Comment by neilzar** [comment]
I updated node and pm2 before running the bot for the first time. Node is v10.16.2 and pm2 is v3.4.0. All other packages are also up to date.

It may have been a hidden character... I just updated the config by manually entering the IP rather than copy-pasting and suddenly it does work. That still leaves the issue of the DNS lookup returning undefined in gamedig.

**Comment by neilzar** [comment]
This was the hidden Unicode that was causing the issues: `9%uFEFF5.216.77.9%uFEFF9`
Damn zero-width space.

**Comment by sonicsnes** [comment]
Hooray, half solved!

In gamedig's DnsResolver.js, can you add this code just below `this.logger.debug("Standard Resolve: " + host);`?

```
        const result = await dnsLookupAsync(host);
        this.logger.debug("DNS RESULT", result);
```

I'm curious if the util.promisified dns.lookup call on your system is missing the address key for some reason.

**Comment by neilzar** [comment]
Here is the result: 
```
1|ARABot  | Q#1 Query is running with options: { socketTimeout: 2000,
1|ARABot  |   attemptTimeout: 10000,
1|ARABot  |   maxAttempts: 1,
1|ARABot  |   port: 2302,
1|ARABot  |   protocol: 'valve',
1|ARABot  |   type: 'arma3',
1|ARABot  |   host: 'arma1.fkservers.eu',
1|ARABot  |   debug: true }
1|ARABot  | Q#1 DNS Lookup: arma1.fkservers.eu
1|ARABot  | Q#1 Standard Resolve: arma1.fkservers.eu
1|ARABot  | Q#1 DNS RESULT 95.216.73.182
1|ARABot  | Q#1 Found address: undefined
1|ARABot  | Q#1 Requesting info ...
1|ARABot  | Q#1 undefined:2302 UDP-->
1|ARABot  | Q#1 Buffer length: 25 bytes
1|ARABot  | ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
1|ARABot  |             T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
1|ARABot  | 65 72 79 00
1|ARABot  | e  r  y
1|ARABot  | Q#1 UDP timeout detected
1|ARABot  | Q#1 Query failed with error Error: UDP - Timed out after 2000ms
1|ARABot  |     at Timeout.setTimeout (/home/botuser/discord-ara-bot/node_modules/gamedig/lib/Promises.js:7:25)
1|ARABot  |     at ontimeout (timers.js:436:11)
1|ARABot  |     at tryOnTimeout (timers.js:300:5)
1|ARABot  |     at listOnTimeout (timers.js:263:5)
1|ARABot  |     at Timer.processTimers (timers.js:223:10)
```

**Comment by sonicsnes** [comment]
That's definitely the issue. Promisified dns.lookup should be returning an object that looks like `{address: 'ip', family: 'ipv4'}`. In your case, it looks like it's just returning the ip by itself, which means it isn't respecting the promisify rules. I've tested using your version of nodejs, and it still worked properly for me. Are you using some sort of transpiler as well? Maybe babel?

**Comment by neilzar** [comment]
I can't find any such packages being used as dependencies and I am not using them myself either. I have also been using the exact same packages on Windows 10 and on CentOs, but only when running using pm2 in CentOs does the issue arise.
