### ISSUE TITLE
Minecraft versus Minecraft PE/BE disparities for vanilla java edition on all major server implementations.

### ISSUE THREAD

**Issue by sustained** [sonicsnes/node-gamedig#136]
I tested **node-gamedig** on Minecraft 1.14.4 with 3 different server implementations:

- PaperMC
- SpigotMC
- Vanilla

[Here are the results](https://gist.github.com/sustained/fc710897f2eb291f60aed7047393fd2c).

--------

# Findings

My findings are basically summarised as follows:

### None of the server implementations...
- accept queries if `enable-query` is set to `false` in `Server.properties`.

### All of the server implementations...
- accept queries if `enable-query` is set to `true`.
- provide ALL online players rather than just a sample.
- provide only a name for the online players - no UUID.

### None of the server implementations...
- report the name correctly (always blank) however the name is always available via `raw.description.text` - so this is an easy fix.

### All of the server implementations...
- accept queries no matter the value of the `enable-query` option in `Server.properties`.
- seem to provide a sample of online players. I can't figure out if it is some ratio/percentage of online players or a simple maximum (the highest I've seen on any server tested is a sample of 12).
- provide both a name and a uuid for the player samples.

----

There are several things I don't understand here and several confusing aspects.

1. Where does the player sample even come from? It seems to me that the server isn't even supposed to return any players at all when `enable-query` is set to `false` and yet we get this sample which even includes UUIDs (which is more information than when `enable-query=true`!). This defies logic and expectations!
2. If a sample is possible with the `minecraft` game-type then why are *all* of the player objects in the players array empty objects? Clearly a bunch of them could be populated. I believe this may be a bug.
3. Why is the name not populated with the value of `raw.description.text`?

I'll look into a PR for points 2 and 3 if you want as they seem like simple changes that don't require intimate knowledge of the protocols and libraries involved.

As for point 1... I am completely and absolutely lost. None of it makes sense to me.

----

For my own uses I am going to basically have to query the server with `minecraftpe` and if those queries fail then fall back to `minecraft` and presume that `enable-query=false` and provide reduced functionality for such servers.

Do you feel it is out of the scope of this project to have some method of falling back to the other in this way?

If so, okay that's fair but do you not think that we should try to align the formats of the responses between the two game types as much as is possible?

**Comment by sustained** [comment]
Edited to fix certain bullet points being under incorrect headings.

**Comment by sonicsnes** [comment]
`Where does the player sample even come from?`

Even when enable-query is false, minecraft still responds to a special server list ping packet (which is separate from the query packet). This server list ping usually includes a small sample of the connected players.

`If a sample is possible with the minecraft game-type then why are all of the player objects in the players array empty objects?`

It was a bug. Should be fixed now! :)

`Why is the name not populated with the value of raw.description.text?`

This should also now be fixed.

Try out 2.0.15! :)

**Comment by sustained** [comment]
@sonicsnes Thank you! :heart:
