### ISSUE TITLE
Minecraft Bedrock Server(bds) can't get infomation

### ISSUE THREAD

**Issue by Guadeloupu** [sonicsnes/node-gamedig#139]
I user the official mc bds server download from
https://www.minecraft.net/en-us/download/server/bedrock/
And I can't get info by using gamedig  with type of minecraft or minecraftpe or minecraftping or minecraftbe.
But I can use mcpe-ping( npm install --save mcpe-ping ) to get my server's info.
Maybe it's because of  The bedrock server don't have "enable-query" option.

**Comment by sonicsnes** [comment]
Hi, do you have a server that is currently online that we can test with?

**Comment by Guadeloupu** [comment]
> Hi, do you have a server that is currently online that we can test with?

game.m-c.fun:19132

**Comment by sonicsnes** [comment]
Please re-open if this is still an issue in the latest version.

**Comment by marvinlehmann** [comment]
Not OP but I can't get gamedig working with the official bedrock server. Only custom servers like NukkitX or PocketMine-MP.

To query an official bedrock server we can send the following UDP RakNet message:

Field (Ordered) | Length (Bytes) | Value | Note
-------------------|----------------|-------|------
Message ID | 1 | 0x01 | ID_UNCONNECTED_PING (enum constant)
timestamp / Ping ID ? | 8 | e.g. 129976706 | can be zeroed
Offline Message Data ID | 16 | 0x00ffff00fefefefefdfdfdfd12345678 | OFFLINE_MESSAGE_DATA_ID (constant)
Client GUID? | 8 | e.g. 837356d3d01c0984 | can be zeroed

Response:

Field (Ordered) | Length (Bytes) | Value | Note
----------------|----------------|-------|------
Message ID | 1 | 0x1c | ID_UNCONNECTED_PONG (enum constant)
timestamp / Ping ID ? | 8 | e.g. 129976706 |
Server GUID ? | 8 | e.g. a2271cdba70860f9 |
Offline Message Data ID | 16 | 0x00ffff00fefefefefdfdfdfd12345678 | OFFLINE_MESSAGE_DATA_ID constant
"Server ID string length" | 2 | e.g. 88 | depends on the content
"Server ID string" | var | MCPE;LinuxGSM;388;1.13.0;0;10; 11684339487961800953;Bedrock level;Survival;1;19132;19133; | explained below...

"Server ID string" (Wireshark calls this field like that):

Field | Example / Value | Note
-----|------------------|------
Game / Edition | MCPE |
Server Name | LinuxGSM |
Protocol Version | 388 |
Server Version | 1.13.0 |
Player Count | 0 |
Player Limit | 10 |
Server ID ? | 11684339487961800953 |
Map / World | Bedrock level |
Game Mode | Survival |
Nintendo Limited ? | 1 | 0/1 - true/false
IPv4 Port | 19132 |
IPv6 Port | 19133 |

The mentioned custom servers also support this query but omit the port numbers in the "Server ID string".

Used sources:
https://github.com/NukkitX/Protocol/blob/master/bedrock/bedrock-common/src/main/java/com/nukkitx/protocol/bedrock/BedrockPong.java#L104
https://github.com/xPaw/PHP-Minecraft-Query/blob/master/src/MinecraftQuery.php#L201
https://github.com/facebookarchive/RakNet/blob/master/DependentExtensions/Swig/InternalSwigItems/InternalSwigWindowsCSharpSample/InternalSwigTestApp/SwigFiles/DefaultMessageIDTypes.cs
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol.xml
and Wireshark :)

**Comment by sonicsnes** [comment]
@marvinlehmann Got an example IP that doesn't work?

**Comment by marvinlehmann** [comment]
@sonicsnes Unfortunately not because I don't have a root server or something similar.
But you can easily download the server from https://www.minecraft.net/en-us/download/server/bedrock/ and directly start it after unzipping it. No further configuration required. The standard ipv4 udp port is 19132, also logged in the console.

**Comment by Guadeloupu** [comment]
The latest version still doesn't work with minecraft bedrock server(bds)
link: https://www.minecraft.net/en-us/download/server/bedrock/

**Comment by madStEvil** [comment]
Can someone reopen or merge this thread, please.
Its still an issue! see also: [https://github.com/sonicsnes/node-gamedig/issues/146](url)
