### ISSUE TITLE
Query works on my pc but doesnt work on my vps

### ISSUE THREAD

**Issue by ForceBlood** [sonicsnes/node-gamedig#150]
So when I try to query a fivem server (ex. 145.239.150.71) I can get the results but then I run the program on my vps it fails to query the server. How can I fix this?

**Comment by xcpep** [comment]
Please try the following and let us know what happens:

Test querying a different FiveM Server

If 1 **fails** then check your firewall settings on the VPS.
If 1 **succeeds** then try to ping and traceroute the server.

If you cannot ping/traceroute the server then it is possible that the server is blocking your IP/Subnet/ASN.
