### ISSUE TITLE
CS:GO players object is empty

### ISSUE THREAD

**Issue by SzAkos** [sonicsnes/node-gamedig#16]
Hi! 

I set up everything and it's working fine except the players object what I get.
There are many player objects as many players are on the server but they are empty.
Is it something with the server itself?

Thanks.

**Comment by xCausxn** [comment]
I will test tonight with my CS:GO server and see what i can find out :D

I will post my results here after i test them on my website version of Gamedig at https://gamerlabs.net

**Comment by sonicsnes** [comment]
Querying for players on GO requires cvar

host_players_show 2

I suppose this should be documented in gamedig as well.
