### ISSUE TITLE
Teamspeak 3 doesn't work

### ISSUE THREAD

**Issue by atheleron** [sonicsnes/node-gamedig#17]
server is online I'm connected to it
but gamedig says: server is offline 
when i try to use global gamedig command
i get error: **TCP Watchdog Timeout**

ts3 server is on default port 9987 and its query port is 10011 what could be wrong ??

**Comment by xCausxn** [comment]
Hello @atheleron ,

I forgot to add this to the website but will add it to the FAQ soon.

Please make sure that the guest server group has the following permissions:

Virtual Server
-- b_virtualserver_info_view
-- b_virtualserver_channel_list
-- b_virtualserver_client_list
Group
-- b_virtualserver_servergroup_list
-- b_virtualserver_channelgroup_list

If you are still having problems please dont hesitate to respond to this thread 

Regards
xCausxn

**Comment by atheleron** [comment]
niceee i change permissions and now everything works :D thank you
