### ISSUE TITLE
multiple queries

### ISSUE THREAD

**Issue by atheleron** [sonicsnes/node-gamedig#18]
is there any way of multiple queries for example I need TS3 and Minecraft in same query ??

**Comment by sonicsnes** [comment]
Gamedig supports running an unlimited number of queries on parallel, simple run a separate Gamedig.query for each query you would like to run. Doing this in parallel is more of a javascript exercise.

Here's a quick example I whipped up. Please note that this pattern may not be applicable to your use case:
https://gist.github.com/sonicsnes/3b5d566d6008e5b1e129
