### ISSUE TITLE
Ark not working on runkit.com

### ISSUE THREAD

**Issue by axi92** [sonicsnes/node-gamedig#181]
https://runkit.com/embed/rboob2jeg4b8
https://www.battlemetrics.com/servers/ark/6862889

```
const Gamedig = require("gamedig")
Gamedig.query({
    type: 'arkse',
    host: '173.249.54.252',
    port: '27017'
}).then((state) => {
    console.log(state);
}).catch((error) => {
    console.log("Server is offline");
    console.log(error);
});
```
Any Ideas why this is not working?

**Comment by sonicsnes** [comment]
It works fine when I run it locally (`gamedig --type arkse --debug 173.249.54.252:27017`). I imagine runkit scripts execute inside some form of container which doesn't allow the reponse udp packets to route back to the process.
