### ISSUE TITLE
Add support for RCon

### ISSUE THREAD

**Issue by Cyberuben** [sonicsnes/node-gamedig#19]
I wonder if you have any interest in implementing remote consoles for the protocols you support (possibly with community help). I find your library extremely useful but I would like to be able to execute commands too.

**Comment by centaureof40** [comment]
Hello,
I also seek the support rcon have the advanced information from a server CSGO, css, tf2, etc .., for steamid of connected players.

**Comment by whocodes** [comment]
I'd also love to see some rcon implementation. Its useful and exists for Minecraft as well as the Source engine and some others.

**Comment by xCausxn** [comment]
We do know that RCON exists for most games:P , this library was mainly made to query servers for information (afaik), however I think @sonicsnes will be doing a refactor of this library at some point, so maybe the implementation could be done then (if he wants to :P)

**Comment by sonicsnes** [comment]
I'm going to leave **full rcon** (as in actually sending rcon commands to the server) to other libraries at this point.

Server **queries** using rcon may still be added in the future in #46
