### ISSUE TITLE
UDP watchdog timeout Americas Army PG

### ISSUE THREAD

**Issue by mastrotje** [sonicsnes/node-gamedig#20]
hallo :)
 i'm trying to use these code to query aa pg server. but i always get these error
{ _: [],
  type: 'americasarmypg',
  host: '37.59.203.232',
  port: 8777 }
{"error":"UDP Watchdog Timeout","query":{"host":"37.59.203.232","address":"37.59.203.232","port":8777,"port_query":27020,"type":"americasarmypg","pretty":"America's Army: Proving Grounds"}}

i've tried :
- gamedig --type americasarmypg --host xxx.xxx.xxx.xxx -port 8777 
and
- gamedig --type americasarmypg --host xxx.xxx.xxx.xxx -port 27020 

can somebody help me with that ?

Thx in adv

**Comment by xCausxn** [comment]
gamedig --type americasarmypg --host 37.59.203.232 --port 8777

Works
--port not -port :D
