### ISSUE TITLE
Udp Arma 3 Problem

### ISSUE THREAD

**Issue by krachenko** [sonicsnes/node-gamedig#21]
Servers Arma 3 not query. Produce this error from the website https://gamerlabs.net/query/:
"Could not connect to UDP socket"

**Comment by xCausxn** [comment]
Im looking into the issue now, please stand by :D

**Comment by xCausxn** [comment]
Hmm i will need to debug this issue further, however some servers work and some dont :P

https://api.gamerlabs.net/?type=arma3&host=server2.fragzonegaming.co.uk&port=2302

**Comment by krachenko** [comment]
Thank you very much!! Now work fine. I love this tool you do a very good job congratulations!

**Comment by xCausxn** [comment]
Thank you very much :)

I do it to support sonic :P

**Comment by sonicsnes** [comment]
What is a server that it does not work for?

**Comment by xCausxn** [comment]
Sonic its been solved mate :D

**Comment by krachenko** [comment]
My server is  Arma 3 ip:188 165 200 127 and this is the port 2302 but it now works correctly. Anyway when he failed not worked any server.
Thanks for your support =)

**Comment by xCausxn** [comment]
https://api.gamerlabs.net/?type=arma3&host=188.165.200.127&port=2302

**Comment by krachenko** [comment]
Perfect!! =) Thank you!!!

**Comment by xCausxn** [comment]
Sonic ill submit a pull request later with a little tweak so above maxplayers is players count
