### ISSUE TITLE
https://gamerlabs.net/query/ not working.

### ISSUE THREAD

**Issue by krachenko** [sonicsnes/node-gamedig#26]
I believe that xCausxn is the author of the website, but I have no way to notify does not work, so I put it here.

I've been using the web long for a project in .net

A few days ago does not work in Arma 3 and teamspeak.

Thank you very much for everything and my thanks to xCausxn and sonicsnes for its great library.

**Comment by xCausxn** [comment]
Thanks for letting me know, i will investigate the issue now :) You can contact me directly on twitter via @xCausxn

**Comment by krachenko** [comment]
Thanks, I keep your twitter me, if I need to contact you again.
