### ISSUE TITLE
Rust Servers Players are not in the players array

### ISSUE THREAD

**Issue by xCausxn** [sonicsnes/node-gamedig#28]
After testing a rust server I noticed the numplayers is set, however the players information is not pushed into the array.

Example: https://api.gamerlabs.net/?type=rust&host=198.24.172.202&port=28015

**Comment by Netifriik** [comment]
It probably has to do with how Rust servers are configured. After researching it seems like most of the server query scripts cannot return Rust players or return players with their names as "hidden".

I also found out that Rust does not run Source, so you cannot query it as a Source server (not sure what gamedig uses to query them).

**Comment by sonicsnes** [comment]
This seems to be fixed.
