### ISSUE TITLE
Quake 2 doesn't return correct maxplayers

### ISSUE THREAD

**Issue by Netifriik** [sonicsnes/node-gamedig#29]
While querying a quake 2 server I noticed maxplayers returned 0. The correct "maxplayers" value is under "maxclients" key which is under the raw values.

The server I was querying: 46.22.210.10:27910

**Comment by Netifriik** [comment]
I see TS3 had the same small bug which was fixed:
https://github.com/sonicsnes/node-gamedig/commit/61d239ccd5876a2bbad12228190bef8425388d69

**Comment by xCausxn** [comment]
I will look into it now :)

**Comment by xCausxn** [comment]
https://github.com/sonicsnes/node-gamedig/pull/27

I have added the fixes to my pull request, so sonic should see them soon,

Ive already applied the changes on my webapi (https://api.gamerlabs.net/?type=quake2&host=46.22.210.10&port=27910) so you can see :)

**Comment by sonicsnes** [comment]
Strange that the variables would be named differently on that server. I guess certain q2 implementations use different variable names.

Also surprised about all that dangling whitespace -- I must have started this project way back on n++ with very lax whitespace settings. I should probably normalize all files next time this project gets cleaned up.
