### ISSUE TITLE
Add Support Primal Carnage:Extinction

### ISSUE THREAD

**Issue by kofe88** [sonicsnes/node-gamedig#39]
Unreal Engine 4, port 27015

**Comment by xCausxn** [comment]
Will investigate this game now :)

**Comment by kofe88** [comment]
Yes, 70.164.233.250:27015

**Comment by kofe88** [comment]
Sorry, UE3 =)

**Comment by xCausxn** [comment]
@kofe88 I need a server to test the the library against, otherwise I cannot even attempt it :P

**Comment by kofe88** [comment]
I have a server, what actions do I perform?

**Comment by Netifriik** [comment]
@kofe88 Is the server still up? I might try implementing it myself.

**Comment by kofe88** [comment]
@Netifriik Yes, its use standart Source Query protocol =)

**Comment by Stead68** [comment]
@kofe88 it's a bit late, I guess, but I pushed a pull-request and added what you needed :-)

**Comment by twamp22** [comment]
#50 Merged in February
