### ISSUE TITLE
Fails wth TCP or UDP Watchdog timeout after some amount of checked servers

### ISSUE THREAD

**Issue by marcinc81** [sonicsnes/node-gamedig#43]
Hi there,

thanks for this awesome library! It's amazing. But I noticed one issue and I don't really know why after processing eg. 20-30 server it starts returning timeout errors. But let's start from the beginning. I'm creating another servers ranking page and I have to check every 1-2 minutes around 3k of Minecraft servers. It's simple script, basically I get list from DB, put tasks into queue and start processing with little concurrency, eg. 5. Initially I was thinking timeouts are caused by too high concurrency and real problems with my internet connection throughput. But nope.

Here's my query function (nothing special here):
```
function query_server(host, port, cb) {
	Gamedig.query(
	    {
	        type: 'minecraftping',
	        host: host,
	        port_query: port,
	        udpTimeout: 2000,
	        tcpTimeout: 2000,
	    },
	    function(state) {
	    	cb(state);
	    }
	);	
}
```
Please note the same problem is with query and ping protocols. The script starts fast and then slows down. After 100-200 processed items only one per 10 servers responds, others get TCP or UDP Watchdog timeout. Interesting is this 'slowing down'. Every next query is slower then previous (and finally they get timeout). Do you have any ideas WHY? 

Of course I'm 100% sure all failed servers are online - checked with other tool and GameDig CLI - it was OK, but only fails when GameDig is working longer while.

**Comment by sonicsnes** [comment]
Does this happen if you query the same server 200ish times in series? Are you sure your concurrency limiter is working properly and not spawning another 5 queries after each one completes ;)? Do you have any simple code that results in this issue?

**Comment by marcinc81** [comment]
Hehe no, the queue works pretty well (npm queue). :) I think it's not related to the network connection handling. Now I'm using ping fe01fa (not GameDig lib) and it gives good results. Cheers!

**Comment by bradisbell** [comment]
@sonicsnes Suppose I want to poll a local game server every second?  How could I do this and not get the UDP watchdog timeout?

**Comment by sonicsnes** [comment]
@bradisbell It really depends on the server. Most servers I know of (primarily source engine based) will rate limit you almost immediately if you are pinging that fast, resulting in a bunch of timeouts when it decides to stop responding to you.

If you are certain that your server is not rate-limiting, and you insist on querying that frequently, you should still ensure that only one query is being sent at a time by waiting for the response from one before you send the next.

To avoid using a ton of random sockets, gamedig sends all queries using a single source udp port. When responses come back into that port, it must assign it to the query which was responsible for making the request. If you are making multiple queries to the same server at the same time, it may potentially send all of the responses to one of the queries, and none to the other -- resulting in an unexpected timeout.

**Comment by bradisbell** [comment]
Thanks @sonicsnes .  Is there a mode where gamedig can use a pool of sockets?  I'd like to query 5 or 10 servers at a time.

**Comment by sonicsnes** [comment]
@bradisbell That shouldn't be an issue. The socket reuse would only be an issue if you are querying the _same_ server simultaneously.
