### ISSUE TITLE
Teamspeak 3 should not show a player connecting when scanned

### ISSUE THREAD

**Issue by TheSpartaPT** [sonicsnes/node-gamedig#47]
idk what is happening but when my bot is running on my vps (ubuntu 14.04.5) when it is querying a teamspeak3 server a teamspeak 3 client joins the server called "unknown" and leaves ... but when it is running on my computer (windows 10 pro) it doesn't do it and still queries the teamspeak 3 server the way it was suposed to.
it is anoying af is there a way to fix this or not ?

also when it queries the teamspeak 3 server name if there is this character "|" it saves it like this "\p" ... only happens when querying a teamspeak 3 server, i queried cs go and cs 1.6 and it didn't happened

**Comment by sonicsnes** [comment]
Our implementation follows the ts3 serverquery spec pretty closely:
https://github.com/sonicsnes/node-gamedig/blob/master/protocols/teamspeak3.js
http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

I don't have a server to test with myself (or much time), but I'd be interested if any other query library acts differently.

**Comment by Hammster** [comment]
I can query my ts3 server normally, but the //p encoding is happening, even though its a pretty wired escape (http://www.fileformat.info/info/unicode/char/7c/index.htm)

**Comment by TheSpartaPT** [comment]
I just fixed it, it randomly got to me out of nowhere to replace the \p with | with replace() ... so it would look something like this :
`state.raw.virtualserver_name.replace(/\\p/g, "|")`

**Comment by sonicsnes** [comment]
According to [this thread|http://forum.teamspeak.com/threads/73071-Query-Clients-hide-show], there is actually an option in the client to hide these connections, and I don't believe there is anything we can do on the scanner side of things.
