### ISSUE TITLE
Starbound 1.x can not be queried

### ISSUE THREAD

**Issue by Hammster** [sonicsnes/node-gamedig#48]
Hi there, i've just update some older starbound instances. And it seams that Starbound changed something on the queries 

Our server (does not query)
> gamedig --type starbound --host das-uhrwerk.de --port 21025 (1.1.1)

```
{
"error":"UDP Watchdog Timeout",
"query":{
  "host":"das-uhrwerk.de",
  "address":"85.214.69.208",
  "port":21025,
  "port_query":21025,
  "type":"starbound",
  "pretty":"Starbound"}
}
```

Outdated Public Server (does query)
> gamedig --type starbound --host 208.167.250.40 --port 21025 (Beta v. Glad Giraffe - Update 3)
```
  {
   "name":"A Starbound Server",
   "map":"Unknown",
   "password":false,
   "raw":{
      "protocol":7,
      "folder":"starbound",
      "game":"Starbound",
      "steamappid":65534,
      "numplayers":0,
      "numbots":0,
      "listentype":"D",
      "environment":"W",
      "secure":0,
      "version":"Beta v. Glad Giraffe - Update 3",
      "port":0,
      "rules":{
         "plugins":"none"
      }
   },
   "maxplayers":4,
   "players":[

   ],
   "bots":[

   ],
   "query":{
      "host":"208.167.250.40",
      "address":"208.167.250.40",
      "port":21025,
      "port_query":21025,
      "type":"starbound",
      "pretty":"Starbound"
   }
}
```

**Comment by sonicsnes** [comment]
Someone reported something similar here:
https://steamcommunity.com/app/211820/discussions/1/352788917753612568/

Does it work on a fresh starbound server install?

**Comment by Hammster** [comment]
Okay, the problem has been resolved,

On the update of ´pre-1.0´ to ´1.0´ they added a option to enable/disable the query port and the default value is now false. So if anyone has the same problem set ´runQueryServer´ to ´true´. Anyone updating Starbound should add the option to their config if it is missing.

Thank you for your time @sonicsnes
