### ISSUE TITLE
bin of latest published version is in dos format

### ISSUE THREAD

**Issue by raine** [sonicsnes/node-gamedig#53]
Latest version has broken the CLI tool on OS X.

The file appears to be in dos format.

```
env: node\r: No such file or directory
```

**Comment by sonicsnes** [comment]
That's what I get for using windows.

**Comment by sonicsnes** [comment]
I managed to pull this off by cloning the repo in windows with default git settings (resulting in git converting line endings to crlfs), then publishing to npm inside of windows 10's linux subsystem (which prevented npm from converting the line endings). Lesson learned the hard way. Republished under 0.2.28.

**Comment by raine** [comment]
Thanks. I was curious how that managed to happen.
