### ISSUE TITLE
Relationship with kurt-stolle/node-gamequery

### ISSUE THREAD

**Issue by Genteure** [sonicsnes/node-gamedig#59]
I found another project that basically same as this one. [kurt-stolle/node-gamequery](https://github.com/kurt-stolle/node-gamequery)
I checked commit history, the first commit of this project was in July 2013. kurt-stolle's node-gamequery was in May 2015.
Two projects are extremely similar, basically same README, basically same code structure.
What do you think?

I don't consider this is a legit fork thing since that project's first ( or second should I say ) commit ([e9ab10](https://github.com/kurt-stolle/node-gamequery/commit/e9ab1006bb38831096607ba3c047a54f852f3da8)) says:

>Merged original private project, removed Casual Bananas specific
references. Preparing to make project public.

Obvious he says that project is his own thing, was a private project.
Is this a copycat thing, or just you guys that lucky wrote same code?

/CC @kurt-stolle

**Comment by sonicsnes** [comment]
Thanks for pointing that out. All of the code in this repository was written by me and a few pull request contributors. I've sent over an email clarifying the terms of the MIT license.
