### ISSUE TITLE
Retry query

### ISSUE THREAD

**Issue by xcpep** [sonicsnes/node-gamedig#60]
It would be a nice feature to have, where you can specify the amount of retries gamedig should perform and the time between retries for if a server is offline.

For example, scan a server a max of 5 times with 1 second between scans.

This is something that could easily be implemented by users in their own projects but could also be a nice feature for the package itself.

**Comment by sonicsnes** [comment]
We sort of have this already at the protocol level, since some games (I'm looking at you minecraft!) don't respond to the first request. I agree that an option would be nice.

**Comment by Coriou** [comment]
Needed this too, opened a pull request implementing this option (#73)

**Comment by sonicsnes** [comment]
Fixed by 94815a2 based on #73
