### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by kbrandwijk** [sonicsnes/node-gamedig#61]
Hi, I found no other way to contact you. I received a takedown notice from Github regarding the node-gamequery library I had forked. I had no idea it originated somewhere else.

Be that as it may, I'd like to take this opportunity to apologise. Also, I saw quite a few forks not mentioned in the takedown notice in the 'original' copy: https://github.com/kurt-stolle/node-gamequery/network/members.

I will remove the repo immediately.

Kind regards.

**Comment by ryush00** [comment]
Hi. I received DMCA takedown request, too. I really apology about it.

I have removed my repositories that were forked from his repository, and I made Pull request of my contribution. (see #62)
Please check it out too.

Thanks,

**Comment by sonicsnes** [comment]
No worries -- I appreciate the contributions. If you need any changes, free free to make a fork or a pull request 😄
