### ISSUE TITLE
[React native] Unable to resolve module `dgram`: Module does not exist in the module map

### ISSUE THREAD

**Issue by vladkolodka** [sonicsnes/node-gamedig#63]
When I use this library in reaact-native project, I'm receiving this error:

> error: bundling failed: "Unable to resolve module `dgram` from `E:\\Desktop\\New folder\\untitled\\node_modules\\gamedig\\lib\\index.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

Tried to install `dgram` directly in the gamedig library folder, but it does not help.

**Comment by sonicsnes** [comment]
Gamedig is written for node.js, which provides `dgram` as an internal package. You may be able to shim dgram with a package such as [react-native-udp](https://github.com/tradle/react-native-udp), but it hasn't been tested.
