### ISSUE TITLE
Stable return values

### ISSUE THREAD

**Issue by PMCJohn** [sonicsnes/node-gamedig#69]
Hello,

I'm not familiar with gamedig and I'm attempting to get the players and maxplayers for my unturned server(IP: GangsRP.playat.ch -- Server is down a lot).

I'm using a callback and when making an output format for the variables I want to list the max players vs players online(ex: 5/24 Players online). When attempting this an error is made stating that the variable player isn't defined, how would I grab the variable player? Also when I put it in the function arguments it doesn't run the function at all.

My Code -- discord.js:

```js
var loading = message.guild.emojis.find('name','loading');
const m = await message.channel.send(`Checking Server Status ${loading}`);

Gamedig.query({
	type: 'unturned',
	host: 'GangsRP.playat.ch',
	port: '27015',
	note: message
},
async (e,state) => {

	if(e){
		var emoji = message.guild.emojis.find('name','xmark');
		var embed = new Discord.RichEmbed()
			.setColor("0xaa0000")
			.setAuthor("Gang's RP Server Status", bot.user.avatarURL)
			.setDescription(`**The server is: \`Offline\`** ${emoji}`)
		m.edit({embed});
		console.log(e);
	} else {
		var emoji = message.guild.emojis.find('name','check');
		var embed = new Discord.RichEmbed()
			.setColor("0x00aa00")
			.setAuthor("Gang's RP Server Status", bot.user.avatarURL)
Player check ->	.setDescription(`**The server is: \`Online\`** ${emoji}\n\n**Name:** Gang's RP - [ Roles, Kits, TPA, NO KOS, 8x Bases ]\n**IP Address:** GangsRP.playat.ch\n**Port:** 27015\n**Players:** ${players.length}\/${maxplayers}`)
		m.edit({embed});
	}
});
```

**Comment by PMCJohn** [comment]
Sorry, I'm stupid I didn't know maxplayers and players was returned as a class of state. Closing thread.

**Comment by sonicsnes** [comment]
Cool! Note that gamedig also works with promises, so (since it appears you are using it within an async function already), you can just do

```const state = await Gamedig.query({
	type: 'unturned',
	host: 'GangsRP.playat.ch',
	port: '27015',
	note: message
});```
