### ISSUE TITLE
{"error":"UDP Watchdog Timeout"}

### ISSUE THREAD

**Issue by omarAjmi** [sonicsnes/node-gamedig#74]
Hi, i am trying to use gamedig after installing it globaly with "npm install gamedig -g".
when i hit gamedig --type arma3 --host 217.182.6.114 --port 2302 for example it throws:
{"error":"UDP Watchdog Timeout"}
it's my first time using it so forgive my ignorance.

**Comment by Coriou** [comment]
The error is pretty clear : the request timed out

With the current implementation, the timeout is fixed at 1 second and you can't really change it globally. I opened a PR to support this (#72)

Your problem is either that the server is actually down, or that it's too slow (could be too far way from you too) to reply in under 1 second

**Comment by omarAjmi** [comment]
sorry for late reply.
after almost 2 weeks dealing with this module i can't really rely on it for my huge project..it works for 3/10 queries for the same server. i know most of the time it's because of the servers that  i query but i can't find a better solution.
any suggestions for a reliable solution?

**Comment by Coriou** [comment]
I'm not the author of the module, all the magic and the actual work here is in parsing the responses from the servers. It's an ancient protocol, that can vary greatly between games. The underlying technology provided by Steam is - to be a bit blunt about it - quite shit.

I think the inconsistencies you're experiencing are due in part to that, and I don't think there's another solution (no other - more modern - protocol that I know of, and based on my research, this is already one of the most comprehensive library out there).

I would however increase the global timeout to see if it fixes some of your problems, for me it did very significantly. For instance, when pinging 10k servers at a 1s timeout I will get something like 6k replies. With a 2s timeout, I'll get 8 or 9k. Maybe it's your problem too, just servers taking a while to reply.

If you want to try this right now without messing around to much, uninstall the official Gamedig (`npm uninstall gamedig`) and install my version which has all the PRs currently opened merged into main (`npm i git+https://github.com/Coriou/node-gamedig.git`). It just will give you a few more options, but won't break your existing code. Then, increase the timeout globally (`GameDig.query({ type: 'XXX', host: 'xxx.xxx.xxx.xxx', port: xxx, timeout: 2000})`) and try again. If you don't see a real improvement after doing that, then maybe you can open a new issue with the extensive logs from Gamedig in debug mode and maybe the real problem will be identified.

**Comment by sonicsnes** [comment]
Hi, sorry for the delayed reply. You can actually already increase the udp watchdog timeout by passing `udpTimeout: 3000` (or even higher) along with your query options.

**Comment by omarAjmi** [comment]
thank you all for the detailed answers, you guys are awesome and this module is awesome, i'll try to do all your recommendations mentioned above. you are a great team.

**Comment by Vistril** [comment]
Apologise in advance for the bump, but mine still doesn't work even after passing socketTimeout: 5000. I'm attempting to query a Garry's Mod server.

`gd.query({
   type: 'garrysmod',
   host: 'IP Removed due to confidentiality reasons', //Yes, I've ensured it's correct
   port: 27015,
   socketTimeout: 5000,
}).then((state) => {
   console.log(state);
}).catch((error) => {
    console.log(error);
});
Error: Failed all 1 attempts
    at QueryRunner.run (/home/runner/node_modules/gamedig/lib/QueryRunner.js:88:21)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 5000ms
    at Timeout.setTimeout (/home/runner/node_modules/gamedig/lib/Promises.js:7:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

Let me know what you've got, thanks. 👍

**Comment by hennyumut** [comment]
Merhaba, 'gamedig' sistemini kullanıyorum fakat söyle bir hata alıyorum: "Error: Failed all 1 attempts" - ('gamedig' versiyonum: 2.0.20) Kodun tamamı;

`Gamedig.query({
      type: 'csgo',
      host: sunucuIP,
      socketTimeout: 3000
  }).then((state) => {
    let emb = new Discord.RichEmbed()
    .setTitle(state.name)
    .setColor("#E79E12")
    .setTimestamp()
    .setImage(`https://www.gametracker.com/server_info/${sunucuIP}:27015/b_560_95_1.png`)
    .setFooter(`${message.author.username} tarafından istendi!`, message.author.avatarURL)
    .addField("IP Adresi", sunucuIP, true)
    .addField("Oyuncular", state.raw.players.length + " / " + state.maxplayers, true)
    .addField("Harita", state.map, true)
    .addField("Sunucuya Bağlan", `steam://connect/${sunucuIP}`, true)
    .addBlankField()
    .addField("GameTracker'da biz;", `[GameTracker'a gitmek için tıkla!](https://www.gametracker.com/server_info/${sunucuIP}:27015/)`, false)
    message.channel.send(emb).catch()
  }).catch((error) => {
    return message.channel.send(`${error}`)
  });`
