### ISSUE TITLE
"Looking for maintainers"

### ISSUE THREAD

**Issue by Coriou** [sonicsnes/node-gamedig#77]
I think you're not maintaining this library anymore and you should mention that you're looking for maintainers, eventually pick one candidate and just allow the project to evolve and be updated please. 

Right now it's a dead project which is a shame because a lot of hard preliminary work got done and rewriting if from scratch would just be kind of a waste of time.

Thank you for considering it

**Comment by sonicsnes** [comment]
I still maintain this project on a periodic basis amidst others. Pull requests are very infrequent, and at this point I do not believe that a team or dedicated maintainer is required here. If I have not resolved your pull requests to your satisfaction, please let me know on the specific threads. Thanks.

**Comment by Coriou** [comment]
Alright, I kinda jumped the gun here, my bad.

I am a very active user of the library and got a bit frustrated that I got had to use to my own fork of the library to use the features that I needed and weren't really "custom" (what I mean is that you could easily argue that they should be default features of such a project).

Also, thanks for implementing the PRs
