### ISSUE TITLE
Game Request, KSP:DMP (Kerbal Space Program: Dark Multiplayer Mod / Protocol)

### ISSUE THREAD

**Issue by Starystars67** [sonicsnes/node-gamedig#78]
Please add support for dmp, found here: https://d-mp.org/
I will take a look at the /reference folder and see if i can create it for you before you get back to me.

Thanks

PS Awesome package

**Comment by sonicsnes** [comment]
Seems like this query protocol requires knowing the httpPort, but I wasn't able to find any available online. Do you have a server running I could check?

**Comment by Starystars67** [comment]
Hello, Yes i have a server and the port your looking for is 6702 :) Hope this helps. If you have a more private way i can contact you that would be good as i do not want to publicly give away the address of this server. Thanks

**Comment by sonicsnes** [comment]
Feel free to email the IP to mmorrison@pon4.net
