### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by xedom** [sonicsnes/node-gamedig#82]
hello,

how can i take the server list of all arma 3 server?
how can I see what mod uses the server?

**Comment by xcpep** [comment]
Sorry for the late reply, but you need to query the steam master list to get all arma 3 servers.

**Comment by xcpep** [comment]
@xedom to see the mods, you would have to parse the response received by gamedig.

I think its safe to close this issue.

**Comment by sonicsnes** [comment]
Aside from the hacky tribes1 master server support, gamedig does not support querying master server lists. There is no intention to expand this support at the current time.
