### ISSUE TITLE
[Request] Battalion 1944

### ISSUE THREAD

**Issue by bbashy** [sonicsnes/node-gamedig#84]
Hi,

I would submit a PR but I'm not too familiar with JavaScript and which protocol it should use.

Game: Battalion 1944
Site: http://battaliongame.com
Wiki: http://wiki.battaliongame.com
Steam App ID: 805140

Source (value) should work with some different params. It uses a separate query port which is port+3

**Comment by sonicsnes** [comment]
Added in 1.0.46
