### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by Murgator** [sonicsnes/node-gamedig#86]
Hi ! I get "Invalid JSON" error when i query this fivem server: 92.42.45.234:32060

However i have updated the files fivem.js and quake2.js ...

Do you have an idea ? yet the JSON file looks good ...

Thank you in advance
David

Files:
https://gyazo.com/735eded17de40b310e1a6840bc1c7469
https://gyazo.com/465822a73435fe2de4119f5a2e2c37a7

**Comment by xCausxn** [comment]
./bin/gamedig.js --type fivem --host 95.213.204.19 --port 30120

I tried another server and it seems to be querying fine ?

**Comment by sonicsnes** [comment]
It seems like the server is no longer online. If you are still having this issue, please re-open.
