### ISSUE TITLE
Added typings to DT

### ISSUE THREAD

**Issue by ivansieder** [sonicsnes/node-gamedig#87]
@sonicsnes could you eventually review it or check it if I missed something?

DefinitelyTyped/DefinitelyTyped#28449

**Comment by ivansieder** [comment]
The types have been merged into DT, so eventually remember to update them with major and minor updates.

**Comment by sonicsnes** [comment]
Thanks for the typings! They look good to me -- for now.

I'm not sure I'll be able to keep them extremely up-to-date since I don't use typescript myself, but I don't anticipate many api changes in the near future.

**Comment by ivansieder** [comment]
I'll keep an eye on it, too, and update them eventually with newer gamedig releases, should they introduce breaking changes! Keep the good work up!
