### ISSUE TITLE
SCUM not working with type "unreal"

### ISSUE THREAD

**Issue by Ryan-J-D** [sonicsnes/node-gamedig#88]
The new game SCUM https://store.steampowered.com/app/513710/SCUM/ is not working with the "unreal" type for connection.

I am assuming it's needing a new protocol added to this package? :)

**Comment by sonicsnes** [comment]
I don't know much about the unreal 4 engine query protocol, but `unreal` is likely not the correct client protocol to use. `unreal` refers to the game "Unreal" (you know, from 1998, before Unreal Tournament). That game used the gamespy1 query protocol.

You might have better luck using `ut3`, which is the query protocol from unreal tournament 3 (not based on gamespy). Please let us know if it works, so we can either give it a real game id or figure out the problem 😄

**Comment by sonicsnes** [comment]
Actually, with unreal engine 4's steamworks integration, and since Tower Unite uses the valve query protocol, it might be worth trying `protocol-valve` as well.

**Comment by Murgator** [comment]
Apparently "protocol-valve" does not work... 
Here are scum server IP online that you can test:
176.57.135.41:28802 (SCUM Downunder #1 - BigDGaming.net)

**Comment by xCausxn** [comment]
I am trying to open a dialog with some of the SCUM developers to see if we can get a definite answer.

I ran a small script to try every protocol (one can hope for it to work...)

The only other thing I can think of prior to buying the game and testing it is that the query ports are closed as if I remember correctly only gportal are hosting them currently

**Comment by Ryan-J-D** [comment]
Hey @xCausxn sorry for the late reply.

You can feel free to test with this IP for my server 176.57.181.7:28602 (Query Port: 28615)

After some digging around however it looks like this game has not implemented any sort of query protocol just yet.

**Comment by xCausxn** [comment]
Thanks for the info, will check it out after work

**Comment by sonicsnes** [comment]
@Ryan-J-D Did you set the query port 28615 yourself? It would be strange if they let you configure a query port, but didn't have querying implemented.

**Comment by Ryan-J-D** [comment]
@sonicsnes - nope. This is the info provided by the shared host they are partnered with.

**Comment by sonicsnes** [comment]
Huh, strange that they would provide a query port that does nothing.

**Comment by sonicsnes** [comment]
Feel free to re-open if they provide a real query protocol 😄
